name: local
variables:
  - name: baseUrl
    value: http://localhost:3000
  - name: token
    value: ""
  - name: itemId
    value: ""
  - name: orderId
    value: ""
  - name: mpOrderId
    value: ""
  - name: mpTestBuyerEmail
    value: ""  # POST /users/test_user no Mercado Pago
